### ISSUE TITLE
Invalid Rider folder when having multiple installs for Rider

### ISSUE THREAD

**Issue by nojaf** [RendleLabs/dotnet-rider-cli#1]
I have two installs in my toolbox for Rider, the stable version and the EAP.

![jetbrains-toolbox](https://user-images.githubusercontent.com/2621499/43738024-91b30d7a-99c3-11e8-82ca-dbed95bc2b4d.png)

This results into a slightly different folder structure.

![rider-stable](https://user-images.githubusercontent.com/2621499/43738049-a29cb64a-99c3-11e8-899b-ab74095e120c.png)

I have two folders under `Rider` (ch-0 and ch-1). The tool should look into those folders to find the correct `.channel.settings.json` file and determine the latest build.

**Comment by ThatRendle** [comment]
Should be working as expected in the latest build (`>=1.0.4`)

**Comment by nojaf** [comment]
Works indeed with 1.0.5
